---

- name: Instalar gnugp
  ansible.builtin.apt:
    name: gnupg
    state: present
    update_cache: true


- name: Agregar clave GPG
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present


- name: Agregar repositorio terraform
  ansible.builtin.apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
    state: present


- name: Instalar terraform
  ansible.builtin.apt:
    name: terraform
    state: present
    update_cache: true

...